openapi: 3.0.2
servers: []
info:
  version: "0.1-SNAPSHOT"
  title: GA4GH service-info API specification
  description: GA4GH service-info specification.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /service-info:
    get:
      description: Get information about the service
      operationId: getServiceInfo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
components:
  schemas:
    ServiceInfo:
      type: object
      required:
        - id
        - name
        - version
      properties:
        id:
          type: string
          description: Unique ID of this service. Reverse domain name notation is recommended, though not required.
          example: 'org.ga4gh.service'
        name:
          type: string
          description: Name of this specific service.
          example: '1000 Genomes Project'
        description:
          type: string
          description: Description of the service.
          example: 'The 1000 Genomes Project is the largest public catalogue of human variation and genotype data.'
        documentationUrl:
          type: string
          description: URL of the documentation of this service (RFC 3986 format).
          example: 'https://docs.example.com'
        version:
          type: string
          description: Version of the service.
          example: '0.1'
